function love.conf(t)
    t.title = "LÖVE und PANZER Server" -- The title of the window the game is in (string)
    t.author = "Landon Manning"  -- The author of the game (string)
    t.url = nil                  -- The website of the game (string)
    t.identity = nil             -- The name of the save directory (string)
    t.version = "0.8.0"          -- The LÖVE version this game was made for (string)
    t.console = true             -- Attach a console (boolean, Windows only)
    t.release = false            -- Enable release mode (boolean)
    t.screen = false
    t.modules.joystick = false   -- Enable the joystick module (boolean)
    t.modules.audio = false      -- Enable the audio module (boolean)
    t.modules.keyboard = false   -- Enable the keyboard module (boolean)
    t.modules.event = true       -- Enable the event module (boolean)
    t.modules.image = false      -- Enable the image module (boolean)
    t.modules.graphics = false   -- Enable the graphics module (boolean)
    t.modules.timer = false      -- Enable the timer module (boolean)
    t.modules.mouse = false      -- Enable the mouse module (boolean)
    t.modules.sound = false      -- Enable the sound module (boolean)
    t.modules.physics = false    -- Enable the physics module (boolean)
end
